hn_feedback = (
    "based on the state the action is not helping.",
    "the action is ineffective based on the state.",
    "the state shows this action is unhelpful.",
    "the state indicates this action is not effective.",
    "this action does not benefit the current state.",
    "the state confirms this action is unsuitable.",
    "the state makes this action ineffective.",
    "the state shows this action is disadvantageous.",
    "the state validates that this action is not helpful.",
    "the state reveals this action is unproductive.",
    "this action falls short given the state conditions.",
    "the state suggests this action is suboptimal.",
    "this action fails to utilize the current state.",
    "the state undermines the success of this action.",
    "this action is misaligned with the state context.",
    "the state hinders this action performance.",
    "this action clashes with the state requirements.",
    "the state exposes the flaws in this action.",
    "this action struggles under the current state.",
    "the state renders this action impractical.",
    "this action is poorly suited to the state dynamics.",
    "the state contradicts the value of this action.",
    "this action is weakened by the state features.",
    "the state signals this action as a poor fit.",
    "this action falters given the state constraints.",
    "this action does not match what the state requires.",
    "the state does not justify this action.",
    "this action is a poor choice for the current state.",
    "the state and this action are at odds.",
    "this action fails to address the state needs.",
    "choosing this action here is not advisable.",
    "this action is not the right move for this state.",
    "the state makes this action less effective."
)
