hp_move_to_puck_feedback = (
    "Because the puck is not gripped yet, you should now moving to the puck. Because the puck is at {puck}, doing the action {action} would help achieving the puck. Thus,",
    "Since the puck is not yet gripped, moving to the puck is the right next step. The puck's location is {puck}, so taking the action {action} will help reach it. Therefore,",
    "You need to move to the puck because it has not been gripped. The puck is located at {puck}, and performing action {action} aids in reaching it. Hence,",
    "The puck is not yet in your grip, so heading toward it is necessary. Given its position at {puck}, executing action {action} will assist in obtaining it. Thus,",
    "As the puck is still ungripped, your task is to move toward it. Its position is {puck}, and the action {action} facilitates this. Consequently,",
    "Because you have not gripped the puck, approaching it is essential. The puck is at {puck}, and doing action {action} supports this goal. So,",
    "Since the puck remains ungripped, your next move should aim at reaching it. Located at {puck}, the action {action} aligns with this objective. Thus,",
    "The puck is currently ungripped, necessitating movement toward it. Positioned at {puck}, taking action {action} will bring you closer. Therefore,",
    "You should focus on the puck since it is not yet gripped. Positioned at {puck}, performing action {action} is beneficial for reaching it. Hence,",
    "As the puck remains ungripped, moving to it is the logical step. It is located at {puck}, and the action {action} facilitates this process. Thus,",
    "Because the puck is not gripped, heading toward it is required. Situated at {puck}, the action {action} is conducive to achieving it. Hence,",
    "Since the puck is ungripped, advancing toward it is vital. Located at {puck}, performing the action {action} will aid in reaching it. Therefore,",
    "You need to pursue the puck as it is still ungripped. Positioned at {puck}, doing action {action} will help secure it. Thus,",
    "The puck is ungripped, so reaching it should be your priority. Being at {puck}, the action {action} is instrumental in attaining it. Hence,",
    "Because the puck remains ungripped, your focus should be on moving toward it. Located at {puck}, the action {action} supports this objective. Consequently,"
)

hp_move_to_goal_feedback = (
    "Because the puck is gripped, you should now moving to the goal. Because the goal is at {goal}, doing the action {action} would help achieving the goal. Thus,",    
    "Since the puck is already gripped, moving toward the goal is the next step. The goal's location is {goal}, so performing action {action} will help achieve it. Therefore,",
    "With the puck gripped, your task now is to proceed to the goal. The goal is at {goal}, and taking the action {action} aids in achieving it. Hence,",
    "Now that the puck is gripped, heading toward the goal is essential. Positioned at {goal}, executing action {action} supports this goal. Thus,",
    "Because the puck is in your grip, you should focus on reaching the goal. Its location is {goal}, and performing action {action} facilitates this. Consequently,",
    "As the puck is gripped, advancing to the goal is necessary. Situated at {goal}, the action {action} will assist in reaching it. So,",
    "The puck is gripped, so your aim should now be to move to the goal. Located at {goal}, taking action {action} aligns with this objective. Thus,",
    "Since the puck is gripped, you should proceed to the goal. It is positioned at {goal}, and performing action {action} will help achieve it. Hence,",
    "Because the puck is in your possession, heading to the goal is logical. Positioned at {goal}, the action {action} aids in achieving it. Thus,",
    "Having gripped the puck, moving to the goal is your next priority. Located at {goal}, doing action {action} will help attain it. Therefore,",
    "With the puck gripped, your focus should now shift to the goal. Situated at {goal}, the action {action} is conducive to achieving it. Hence,",
    "The puck is already gripped, so advancing to the goal is required. Positioned at {goal}, performing action {action} will help reach it. Consequently,",
    "Since the puck is in your grip, pursuing the goal should be your aim. Being at {goal}, the action {action} facilitates this. Thus,",
    "As the puck is gripped, reaching the goal is your next step. Located at {goal}, the action {action} will aid in achieving it. Hence,",
    "Because you have gripped the puck, your task is to move to the goal. Positioned at {goal}, taking the action {action} supports this goal. Consequently,"
)

hn_move_to_puck_feedback = (
    "Because the puck is not gripped yet, you should now moving to the puck. But executing the action {action} is not helping to achieve the puck at {puck}. Thus,",
    "Since the puck is ungripped, your goal is to move toward it. However, the action {action} does not help achieve the puck at {puck}. Hence,",
    "As the puck remains ungripped, moving to it is necessary. Yet, the action {action} does not assist in reaching the puck at {puck}. Therefore,",
    "The puck is not in your grip, so you should aim to approach it. But doing action {action} does not support obtaining the puck at {puck}. Thus,",
    "Because the puck is still ungripped, heading toward it is required. However, the action {action} does not contribute to reaching the puck at {puck}. Hence,",
    "Since the puck is ungripped, moving toward it is important. Yet, performing action {action} fails to help achieve the puck at {puck}. Thus,",
    "You should now move to the puck as it is not gripped. However, the action {action} is ineffective in reaching the puck at {puck}. Consequently,",
    "As the puck is not in your possession, your task is to reach it. But taking action {action} does not aid in securing the puck at {puck}. Thus,",
    "Because the puck is ungripped, your focus should be on moving to it. Yet, the action {action} does not help achieve the puck at {puck}. Therefore,",
    "The puck remains ungripped, so your priority is to move toward it. However, performing action {action} does not assist in obtaining the puck at {puck}. Hence,",
    "Since the puck is not gripped, advancing toward it is essential. Yet, executing action {action} does not aid in achieving the puck at {puck}. Consequently,",
    "You must aim for the puck as it is ungripped. But the action {action} does not help in reaching the puck at {puck}. Thus,",
    "As the puck is ungripped, heading to it should be your goal. Yet, doing action {action} fails to support this goal at {puck}. Therefore,",
    "Because the puck is not yet gripped, moving to it is necessary. However, taking action {action} does not help achieve it at {puck}. Hence,",
    "The puck is not in your grip, so reaching it is crucial. But the action {action} does not contribute to securing it at {puck}. Consequently,"
)

hn_move_to_goal_feedback = (
    "Because the puck is gripped, you should now moving to the goal. But executing the action {action} is not helping to achieve the goal at {goal}. Thus,",    
    "With the puck gripped, your goal is to move toward the goal. However, performing action {action} does not help achieve the goal at {goal}. Hence,",
    "Since the puck is in your possession, advancing to the goal is necessary. Yet, taking action {action} does not aid in reaching the goal at {goal}. Thus,",
    "As the puck is gripped, heading to the goal is essential. However, the action {action} does not assist in achieving the goal at {goal}. Consequently,",
    "Because you have gripped the puck, moving to the goal is required. But performing action {action} fails to support this goal at {goal}. Therefore,",
    "The puck is gripped, so your next move should target the goal. Yet, doing action {action} does not help achieve the goal at {goal}. Hence,",
    "Having the puck in your grip, you must focus on the goal. However, the action {action} does not aid in reaching it at {goal}. Thus,",
    "As the puck is gripped, advancing toward the goal is crucial. But taking action {action} does not support this at {goal}. Therefore,",
    "Because the puck is gripped, your priority should be the goal. Yet, performing action {action} does not help achieve it at {goal}. Hence,",
    "The puck is in your possession, so reaching the goal is important. However, the action {action} does not contribute to attaining it at {goal}. Consequently,",
    "Since the puck is gripped, heading toward the goal is essential. But doing action {action} does not align with achieving it at {goal}. Therefore,",
    "You have the puck gripped, so moving to the goal should be your aim. Yet, taking action {action} does not help achieve it at {goal}. Hence,",
    "Because the puck is gripped, your task is to proceed to the goal. However, executing action {action} does not support this at {goal}. Consequently,",
    "With the puck gripped, advancing to the goal is the next logical step. Yet, the action {action} does not assist in reaching it at {goal}. Therefore,",
    "The puck is in your grip, so moving to the goal is necessary. However, doing action {action} does not aid in achieving it at {goal}. Hence,"
)

# No tensor included
hp_move_to_puck_feedback_no_tensor = (
    "Because the puck is not gripped yet, you should now moving to the puck. Based on the puck_pos and hand_pos, doing the action would help achieving the puck. Thus,",
    "Since the puck is still not in your grip, your next step should be moving toward the puck. Considering the puck_pos and hand_pos, this action aids in achieving the puck. Therefore,",
    "As you haven't gripped the puck yet, moving to the puck is required. The puck_pos and hand_pos suggest that this action facilitates achieving the puck. Hence,",
    "Because the puck remains ungripped, you need to approach the puck now. Referring to the puck_pos and hand_pos, this action helps achieve the puck. Thus,",
    "You have yet to grip the puck, so moving toward it is necessary. From the puck_pos and hand_pos, the action aligns with achieving the puck. Therefore,",
    "The puck is not currently gripped, so moving to it is the next step. Based on puck_pos and hand_pos, this action supports achieving the puck. Hence,",
    "Since the puck is not yet in hand, you should move toward it. The puck_pos and hand_pos indicate this action helps achieve the puck. Thus,",
    "Without gripping the puck, your focus should be moving toward it. Based on puck_pos and hand_pos, this action aids in getting the puck. Therefore,",
    "Because the puck is not yet gripped, the logical move is to approach it. Considering puck_pos and hand_pos, this action achieves the puck. Hence,",
    "As the puck is still not gripped, your priority is to move to it. The puck_pos and hand_pos show this action leads to gripping the puck. Thus,",
    "The puck remains ungripped, so you should focus on moving toward it. Using puck_pos and hand_pos, this action helps achieve the puck. Therefore,",
    "You need to grip the puck, so moving toward it is essential. Based on puck_pos and hand_pos, the action facilitates gripping the puck. Hence,",
    "Because the puck is not in your grip, you must now approach it. The puck_pos and hand_pos suggest this action aids in achieving the puck. Thus,",
    "Since the puck is ungripped, moving toward it is crucial. From the puck_pos and hand_pos, the action supports getting the puck. Therefore,",
    "As the puck is not yet gripped, your task is to move toward it. Considering puck_pos and hand_pos, this action achieves the puck. Hence,",
    "Without the puck in your grip, you should now move toward it. Based on puck_pos and hand_pos, this action aids in gripping the puck. Thus,",
    "You haven't gripped the puck yet, so moving to it is required. Using puck_pos and hand_pos, this action achieves the puck. Therefore,",
    "The puck remains out of grip, so the next move is to approach it. From puck_pos and hand_pos, this action facilitates gripping the puck. Hence,",
    "Because the puck is not currently gripped, moving toward it is necessary. Based on puck_pos and hand_pos, this action supports achieving the puck. Thus,",
    "Since the puck is ungripped, the action to move toward it is essential. Considering puck_pos and hand_pos, this action aids in gripping the puck. Therefore,",
    "You need to grip the puck, so focusing on moving toward it is key. The puck_pos and hand_pos indicate this action achieves the puck. Hence,",
    "As the puck remains ungripped, the logical step is to approach it. Based on puck_pos and hand_pos, this action facilitates gripping the puck. Thus,",
    "Without the puck in hand, moving toward it is the next logical step. Using puck_pos and hand_pos, this action helps achieve the puck. Therefore,",
    "Since the puck is still not gripped, you should now approach it. From puck_pos and hand_pos, this action supports gripping the puck. Hence,",
    "The puck has yet to be gripped, so moving to it is necessary. Considering puck_pos and hand_pos, this action achieves the puck. Thus,",
    "You need to move toward the puck as it is not gripped. Based on puck_pos and hand_pos, this action helps achieve the puck. Therefore,",
    "Because the puck is not in your grip, you must now move toward it. From puck_pos and hand_pos, this action facilitates gripping the puck. Hence,",
    "As the puck remains ungripped, approaching it is essential. Using puck_pos and hand_pos, this action aids in achieving the puck. Thus,",
    "Since you haven't gripped the puck yet, moving to it is required. The puck_pos and hand_pos indicate this action supports gripping the puck. Therefore,",
    "The puck remains ungripped, so your focus should be on moving toward it. Based on puck_pos and hand_pos, this action helps achieve the puck. Hence,",
    "You need to grip the puck, so approaching it is key. Considering puck_pos and hand_pos, this action aids in gripping the puck. Thus,",
    "As the puck is not yet gripped, moving toward it is necessary. From puck_pos and hand_pos, this action facilitates gripping the puck. Therefore,",
    "Because the puck is not gripped yet, moving toward it is essential. Using puck_pos and hand_pos, this action achieves the puck. Hence,",
    "Since the puck is not in your grip, you should now approach it. The puck_pos and hand_pos suggest this action supports gripping the puck. Thus,",
    "Without the puck in hand, the logical move is to approach it. Based on puck_pos and hand_pos, this action aids in achieving the puck. Therefore,",
    "You need to grip the puck, so moving to it is the next step. Considering puck_pos and hand_pos, this action helps achieve the puck. Hence,",
    "The puck remains ungripped, so moving toward it is crucial. From puck_pos and hand_pos, this action supports gripping the puck. Thus,",
    "As the puck is not yet in your grip, approaching it is key. Based on puck_pos and hand_pos, this action facilitates gripping the puck. Therefore,",
    "Since the puck is ungripped, you must now move toward it. The puck_pos and hand_pos indicate this action helps achieve the puck. Hence,",
    "Because the puck is not gripped yet, your task is to move toward it. From puck_pos and hand_pos, this action achieves the puck. Thus,",
    "You haven't gripped the puck yet, so focusing on moving toward it is necessary. Using puck_pos and hand_pos, this action supports gripping the puck. Therefore,",
    "The puck is still ungripped, so the logical move is to approach it. Considering puck_pos and hand_pos, this action helps achieve the puck. Hence,",
    "Since the puck is not currently gripped, moving toward it is essential. The puck_pos and hand_pos indicate this action aids in gripping the puck. Thus,",
    "Without the puck in hand, you need to move toward it. Based on puck_pos and hand_pos, this action supports gripping the puck. Therefore,",
    "The puck has yet to be gripped, so your focus should be on moving toward it. Using puck_pos and hand_pos, this action achieves the puck. Hence,",
    "Because the puck is not in your grip, approaching it is necessary. From puck_pos and hand_pos, this action aids in gripping the puck. Thus,",
    "As the puck remains ungripped, the logical step is to move toward it. Considering puck_pos and hand_pos, this action supports achieving the puck. Therefore,"
)


hp_move_to_goal_feedback_no_tensor = (
    "Because the puck is gripped, you should now moving to the goal. Based on the goal_pos and hand_pos, doing the action would help achieving the goal. Thus,",    
    "Since the puck is already gripped, your next step is to move toward the goal. Considering the goal_pos and hand_pos, this action aids in achieving the goal. Therefore,",
    "As the puck is in your grip, you should focus on moving toward the goal. The goal_pos and hand_pos indicate that this action facilitates achieving the goal. Hence,",
    "Because the puck is held, your task is now to approach the goal. Based on the goal_pos and hand_pos, this action helps you achieve the goal. Thus,",
    "Having gripped the puck, you need to move to the goal. From the goal_pos and hand_pos, the action aligns with achieving the goal. Therefore,",
    "Since the puck is gripped, moving toward the goal is the next step. Considering the goal_pos and hand_pos, this action supports achieving the goal. Hence,",
    "As the puck is securely held, proceeding to the goal is essential. Using the goal_pos and hand_pos, this action aids in achieving the goal. Thus,",
    "With the puck in hand, you should now move toward the goal. Based on the goal_pos and hand_pos, this action achieves the goal. Therefore,",
    "Because the puck is in your grip, the logical move is to approach the goal. From the goal_pos and hand_pos, this action facilitates achieving the goal. Hence,",
    "Since you have the puck gripped, your focus should now be on moving toward the goal. The goal_pos and hand_pos suggest this action supports achieving the goal. Thus,",
    "The puck is gripped, so your next task is to head to the goal. Based on the goal_pos and hand_pos, this action helps achieve the goal. Therefore,",
    "Having gripped the puck, moving toward the goal is the logical step. From the goal_pos and hand_pos, this action supports achieving the goal. Hence,",
    "Since the puck is already gripped, you should now move toward the goal. Considering the goal_pos and hand_pos, this action aids in achieving the goal. Thus,",
    "With the puck in your grasp, the next step is to approach the goal. Using the goal_pos and hand_pos, this action facilitates achieving the goal. Therefore,",
    "Because the puck is in hand, moving to the goal is the next logical move. Based on the goal_pos and hand_pos, this action supports achieving the goal. Hence,",
    "Having gripped the puck, the logical next step is to move toward the goal. From the goal_pos and hand_pos, this action aids in achieving the goal. Thus,",
    "As the puck is held, you should now focus on moving toward the goal. The goal_pos and hand_pos indicate this action supports achieving the goal. Therefore,",
    "With the puck securely gripped, approaching the goal is the next step. Considering the goal_pos and hand_pos, this action facilitates achieving the goal. Hence,",
    "Since the puck is already in your grip, moving to the goal is essential. Using the goal_pos and hand_pos, this action aids in achieving the goal. Thus,",
    "Because the puck is held, the logical move is to approach the goal. From the goal_pos and hand_pos, this action supports achieving the goal. Therefore,",
    "As the puck is gripped, your focus should now shift to moving toward the goal. Based on the goal_pos and hand_pos, this action helps achieve the goal. Hence,",
    "The puck is securely gripped, so the next step is to move toward the goal. Considering the goal_pos and hand_pos, this action supports achieving the goal. Thus,",
    "Since you are holding the puck, you should now approach the goal. Using the goal_pos and hand_pos, this action aids in achieving the goal. Therefore,",
    "Having the puck gripped, your next action should focus on moving to the goal. From the goal_pos and hand_pos, this action helps achieve the goal. Hence,",
    "Because the puck is already gripped, moving toward the goal is essential. The goal_pos and hand_pos indicate this action facilitates achieving the goal. Thus,",
    "With the puck in your possession, you should now move to the goal. Based on the goal_pos and hand_pos, this action aids in achieving the goal. Therefore,",
    "The puck is gripped, so your priority should be moving toward the goal. From the goal_pos and hand_pos, this action supports achieving the goal. Hence,",
    "As you have gripped the puck, proceeding to the goal is required. Using the goal_pos and hand_pos, this action helps achieve the goal. Thus,",
    "Because the puck is in hand, the logical action is to approach the goal. Considering the goal_pos and hand_pos, this action supports achieving the goal. Therefore,",
    "Having the puck gripped, moving to the goal is the logical next step. Based on the goal_pos and hand_pos, this action aids in achieving the goal. Hence,",
    "Since you have gripped the puck, your next move is to approach the goal. From the goal_pos and hand_pos, this action supports achieving the goal. Thus,",
    "The puck is securely held, so you should now move toward the goal. Using the goal_pos and hand_pos, this action facilitates achieving the goal. Therefore,",
    "Because the puck is gripped, your next focus should be on approaching the goal. Considering the goal_pos and hand_pos, this action supports achieving the goal. Hence,",
    "With the puck in your grip, heading to the goal is essential. Based on the goal_pos and hand_pos, this action aids in achieving the goal. Thus,",
    "Since the puck is already in hand, moving toward the goal is the next logical step. From the goal_pos and hand_pos, this action supports achieving the goal. Therefore,",
    "As you are holding the puck, your next step is to approach the goal. Using the goal_pos and hand_pos, this action aids in achieving the goal. Hence,",
    "The puck is gripped, so your priority should be moving to the goal. Considering the goal_pos and hand_pos, this action supports achieving the goal. Thus,",
    "Having the puck gripped, your next focus should be on moving to the goal. Based on the goal_pos and hand_pos, this action facilitates achieving the goal. Therefore,",
    "Because the puck is held, moving to the goal is essential. From the goal_pos and hand_pos, this action aids in achieving the goal. Hence,",
    "With the puck in your possession, the logical next move is to approach the goal. Using the goal_pos and hand_pos, this action supports achieving the goal. Thus,",
    "The puck is gripped, so your focus should now be on moving toward the goal. Considering the goal_pos and hand_pos, this action facilitates achieving the goal. Therefore,",
    "Since you are holding the puck, moving to the goal is the next logical step. Based on the goal_pos and hand_pos, this action aids in achieving the goal. Hence,",
    "As the puck is securely gripped, your next action should be moving toward the goal. From the goal_pos and hand_pos, this action supports achieving the goal. Thus,",
    "Having gripped the puck, you should now move toward the goal. Using the goal_pos and hand_pos, this action aids in achieving the goal. Therefore,",
    "Because the puck is in your grip, the next logical move is to approach the goal. Considering the goal_pos and hand_pos, this action supports achieving the goal. Hence,",
    "Since you are holding the puck, you should now focus on moving to the goal. Based on the goal_pos and hand_pos, this action facilitates achieving the goal. Thus,",
    "The puck is already gripped, so your priority should be on heading toward the goal. From the goal_pos and hand_pos, this action supports achieving the goal. Therefore,",
    "As the puck is gripped, your next focus should be on moving to the goal. Using the goal_pos and hand_pos, this action aids in achieving the goal. Hence,",
    "With the puck in hand, the logical step is to move toward the goal. Considering the goal_pos and hand_pos, this action supports achieving the goal. Thus,"
)


hn_move_to_puck_feedback_no_tensor = (
    "Because the puck is not gripped yet, you should now move to the puck. However, based on the puck_pos and hand_pos, executing the action is not helping to access the puck. Thus,",
    "Since the puck remains ungripped, you should focus on moving to it, though the current action does not effectively align with the puck_pos and hand_pos. Therefore,",
    "The puck is still not gripped, so your priority is to approach it. Yet, the action seems ineffective considering the puck_pos and hand_pos. Thus,",
    "As the puck remains ungripped, it is necessary to move closer. The current action, however, fails to align with the puck_pos and hand_pos. Therefore,",
    "Given that the puck has not been gripped, moving towards it is essential, but the action is not proving helpful based on puck_pos and hand_pos. Hence,",
    "The puck has not yet been gripped, requiring a move towards it. Unfortunately, the action does not seem to fit the puck_pos and hand_pos. Thus,",
    "Because the puck remains ungripped, advancing towards it is necessary, yet the action executed isn't achieving this, considering the puck_pos and hand_pos. Therefore,",
    "Since the puck is not yet gripped, you should aim to move to it. The action, however, does not match the puck_pos and hand_pos effectively. Thus,",
    "The puck has yet to be gripped, which means movement towards it is required. Still, the action doesn't align well with the puck_pos and hand_pos. Hence,",
    "To grip the puck, you need to move closer, but the current action isn't supporting this task based on the puck_pos and hand_pos. Thus,",
    "Because the puck is still ungripped, it’s time to move to it, although the action isn't assisting as per puck_pos and hand_pos. Therefore,",
    "The puck remains out of reach, requiring you to move toward it. Yet, the action executed doesn't work well with the puck_pos and hand_pos. Thus,",
    "Moving towards the puck is the next step since it is ungripped. However, the action isn't effective in light of the puck_pos and hand_pos. Therefore,",
    "As the puck is not gripped yet, your goal is to move closer, but the action does not properly align with the puck_pos and hand_pos. Thus,",
    "Because the puck is ungripped, you must advance toward it, but the action taken seems unproductive when considering the puck_pos and hand_pos. Therefore,",
    "The puck is ungripped, so the appropriate move is to approach it. Yet, the action doesn't help given the puck_pos and hand_pos. Hence,",
    "With the puck still out of grip, your next action should be to move toward it, though the current execution doesn't align with puck_pos and hand_pos. Thus,",
    "As the puck remains ungripped, moving to it is necessary, but the current action isn't aiding based on the puck_pos and hand_pos. Therefore,",
    "Since the puck is still ungripped, the next logical step is to move to it. Unfortunately, the action doesn't assist as expected with the puck_pos and hand_pos. Hence,",
    "The puck is not yet in hand, and moving to it is required. However, the current action isn't aligned with the puck_pos and hand_pos. Thus,",
    "The ungripped puck necessitates moving toward it, though the action is not assisting effectively as per puck_pos and hand_pos. Therefore,",
    "Because the puck has not been gripped, the immediate step is to approach it, but the action fails to correspond with the puck_pos and hand_pos. Thus,",
    "With the puck ungripped, advancing closer is needed. The action, however, is ineffective based on the puck_pos and hand_pos. Therefore,",
    "The puck remains ungripped, and moving to it is necessary, but the action isn't aligned with the puck_pos and hand_pos. Thus,",
    "Because the puck is out of your grip, the logical next step is to move toward it, though the action isn't working well considering the puck_pos and hand_pos. Hence,",
    "Since the puck is still ungripped, you need to advance toward it. The current action, however, does not support this goal given the puck_pos and hand_pos. Therefore,",
    "As the puck remains ungripped, the next step is to move toward it. Yet, the action is not effective with respect to the puck_pos and hand_pos. Thus,",
    "The puck is not in your grip, so you should move toward it. However, the action isn't aligned with the puck_pos and hand_pos. Therefore,",
    "To reach the puck, moving closer is required, but the current action doesn't match the puck_pos and hand_pos effectively. Hence,",
    "Because the puck is still ungripped, your task is to move toward it. Unfortunately, the action fails to align with the puck_pos and hand_pos. Thus,",
    "The ungripped puck calls for movement closer, though the action isn't proving effective when considering the puck_pos and hand_pos. Therefore,",
    "With the puck ungripped, the next logical step is to approach it, though the current action is misaligned with puck_pos and hand_pos. Thus,",
    "Since the puck has not been gripped, advancing toward it is necessary, but the action executed does not support this goal given puck_pos and hand_pos. Therefore,",
    "The puck remains ungripped, and you need to move to it. Yet, the current action does not seem productive with respect to the puck_pos and hand_pos. Thus,",
    "Because the puck is out of reach, moving toward it is essential. However, the action is not working effectively as per the puck_pos and hand_pos. Therefore,",
    "With the puck still ungripped, the priority is to move closer, though the action fails to align properly with the puck_pos and hand_pos. Hence,",
    "The puck is not yet in your grip, so moving toward it is the next step. The action, however, isn't helping based on the puck_pos and hand_pos. Thus,",
    "As the puck is ungripped, you should focus on moving toward it, but the action executed isn't aligning with puck_pos and hand_pos. Therefore,",
    "Since the puck has yet to be gripped, the required action is to move closer. Still, the execution is ineffective considering the puck_pos and hand_pos. Hence,",
    "Because the puck is ungripped, advancing to it is needed, though the action does not support this based on the puck_pos and hand_pos. Thus,",
    "The puck remains out of your grip, so you should move toward it, yet the action isn't aligning well with the puck_pos and hand_pos. Therefore,",
    "Given that the puck is still ungripped, moving closer is necessary, but the current action does not seem effective when considering the puck_pos and hand_pos. Thus,",
    "The ungripped puck necessitates an approach, though the action currently being taken is ineffective relative to the puck_pos and hand_pos. Hence,",
    "Because the puck is not yet in hand, moving toward it is required. However, the action taken does not align well with the puck_pos and hand_pos. Therefore,",
    "Since the puck remains ungripped, movement toward it is essential. Yet, the action isn't effective when considering the puck_pos and hand_pos. Thus,",
    "The puck has not been gripped yet, so moving toward it is crucial. Unfortunately, the action does not align with the puck_pos and hand_pos effectively. Hence,",
    "With the puck ungripped, your goal should be to advance toward it. However, the action isn't helping based on the puck_pos and hand_pos. Therefore,",
    "The puck is not yet in your grip, requiring movement closer. Still, the current action isn't aiding as per puck_pos and hand_pos. Thus,",
    "To grip the puck, you need to move toward it. Yet, the action doesn't align effectively with the puck_pos and hand_pos. Therefore,",
)


hn_move_to_goal_feedback_no_tensor = (
    "Because the puck is gripped, you should now move to the goal. However, based on the goal_pos and the hand_pos, executing the action is not helping to achieve the goal. Thus,",
    "Since the puck is already gripped, your next step is to move to the goal. Yet, the action being performed does not effectively align with the hand_pos and goal_pos. Therefore,",
    "The puck is in your grip, so moving toward the goal is necessary. Unfortunately, the action doesn't assist in achieving this based on the hand_pos and goal_pos. Hence,",
    "With the puck secured, you should now aim for the goal, but the action does not seem effective given the hand_pos and goal_pos. Thus,",
    "As the puck is already gripped, your task is to move to the goal. The current action, however, fails to align well with the goal_pos and hand_pos. Therefore,",
    "Given that the puck is gripped, advancing to the goal is essential. Yet, the action taken does not correspond effectively to the hand_pos and goal_pos. Hence,",
    "The puck has been gripped, so heading for the goal is required. Unfortunately, the action being executed doesn't fit the hand_pos and goal_pos properly. Thus,",
    "Since the puck is secured, your next move should focus on the goal. Still, the action fails to align with the goal_pos and hand_pos. Therefore,",
    "With the puck in your grasp, progressing toward the goal is necessary. However, the current action doesn't seem effective considering the hand_pos and goal_pos. Hence,",
    "Because the puck is firmly gripped, you should move toward the goal. Yet, the action performed does not support this based on the goal_pos and hand_pos. Thus,",
    "The puck is already secured, which means moving to the goal is the logical step. However, the action being executed does not align well with the goal_pos and hand_pos. Therefore,",
    "Since the puck is gripped, heading to the goal is your next objective. The current action, however, doesn't contribute effectively based on the hand_pos and goal_pos. Thus,",
    "Now that the puck is gripped, moving to the goal is necessary. Unfortunately, the action doesn't work as expected given the hand_pos and goal_pos. Hence,",
    "Because the puck has been secured, the logical move is toward the goal. Yet, the action fails to align with the goal_pos and hand_pos. Therefore,",
    "As the puck is already gripped, your next move is to the goal. However, the action isn't effective in light of the hand_pos and goal_pos. Thus,",
    "The puck is in your hand, so advancing to the goal is required. Still, the current action doesn't align properly with the goal_pos and hand_pos. Hence,",
    "With the puck gripped, the focus should now be on reaching the goal. Unfortunately, the action doesn't align with the hand_pos and goal_pos effectively. Thus,",
    "Since the puck is already gripped, your objective is the goal. However, the action does not support achieving this given the hand_pos and goal_pos. Therefore,",
    "Having secured the puck, your priority is to move to the goal. Yet, the action being performed doesn't align well with the goal_pos and hand_pos. Hence,",
    "Because the puck is in your grip, the next logical step is heading to the goal. Unfortunately, the action doesn't seem productive relative to the goal_pos and hand_pos. Thus,",
    "The puck is gripped, so your next action should target the goal. However, the current action fails to correspond effectively with the hand_pos and goal_pos. Therefore,",
    "Now that the puck is secured, your focus should shift to moving toward the goal. Yet, the action doesn't effectively align with the goal_pos and hand_pos. Hence,",
    "Since the puck is already in your grip, moving to the goal is necessary. However, the current action isn't achieving this based on the goal_pos and hand_pos. Thus,",
    "The puck is firmly gripped, so you should now aim for the goal. Unfortunately, the action doesn't contribute effectively considering the hand_pos and goal_pos. Hence,",
    "Having gripped the puck, the next step is moving to the goal. Still, the action fails to align properly with the goal_pos and hand_pos. Therefore,",
    "As the puck is gripped, you should head toward the goal. However, the current action doesn't match the requirements given the hand_pos and goal_pos. Thus,",
    "With the puck secured, moving to the goal is required. Yet, the action executed doesn't effectively correspond to the goal_pos and hand_pos. Hence,",
    "Because the puck is already gripped, advancing toward the goal is necessary. Unfortunately, the action being taken doesn't align well with the goal_pos and hand_pos. Therefore,",
    "Now that the puck is in your hand, reaching the goal is the priority. Yet, the action doesn't appear helpful considering the hand_pos and goal_pos. Hence,",
    "The puck is secured, so your next move is to the goal. However, the action doesn't align with the goal_pos and hand_pos as expected. Thus,",
    "Since the puck is firmly gripped, moving toward the goal is essential. Unfortunately, the action fails to align effectively with the hand_pos and goal_pos. Therefore,",
    "Having the puck in your grip means your focus should now be on the goal. Yet, the action doesn't correspond effectively to the goal_pos and hand_pos. Hence,",
    "Because the puck is secured, your movement should target the goal. However, the action currently taken doesn't seem effective based on the hand_pos and goal_pos. Thus,",
    "The puck is gripped, requiring you to move to the goal. Unfortunately, the current action is not aligned with the goal_pos and hand_pos. Therefore,",
    "With the puck secured, you need to move toward the goal. Still, the action executed fails to correspond effectively to the goal_pos and hand_pos. Hence,",
    "Since the puck is in your grip, the logical move is toward the goal. Unfortunately, the current action doesn't support this based on the hand_pos and goal_pos. Thus,",
    "Now that the puck is firmly secured, the goal should be your next focus. However, the action doesn't align well with the goal_pos and hand_pos. Therefore,",
    "Because the puck is already gripped, your next step is advancing to the goal. Yet, the action taken doesn't effectively match the goal_pos and hand_pos. Hence,",
    "With the puck in hand, your movement should now be directed toward the goal. Unfortunately, the current action isn't productive given the goal_pos and hand_pos. Thus,",
    "Since the puck is secured, advancing to the goal is required. Still, the action isn't aligning properly with the goal_pos and hand_pos. Therefore,",
    "The puck is firmly gripped, which means your next move is to the goal. However, the action fails to correspond effectively with the goal_pos and hand_pos. Hence,",
    "Having gripped the puck, you should now focus on reaching the goal. Unfortunately, the action doesn't seem helpful given the hand_pos and goal_pos. Thus,",
    "As the puck is secured, moving to the goal is the logical step. Yet, the current action isn't aligned with the goal_pos and hand_pos. Therefore,",
    "The puck is in your grip, so your next objective is the goal. However, the action doesn't support achieving this based on the goal_pos and hand_pos. Hence,",
    "With the puck already gripped, advancing toward the goal is necessary. Yet, the action performed fails to align with the hand_pos and goal_pos. Thus,",
    "Now that the puck is gripped, reaching the goal should be the focus. However, the current action doesn't correspond effectively to the goal_pos and hand_pos. Therefore,",
    "Since the puck is secured, heading to the goal is required. Unfortunately, the action doesn't work well considering the goal_pos and hand_pos. Hence,",
    "Because the puck is firmly gripped, your priority is moving toward the goal. Yet, the current action fails to match the goal_pos and hand_pos. Therefore,",
)
